version: '3'

services:
  pragma_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5433:5432
    command: [ "postgres",  "-c", "log_statement=all" ]

  openwhisk:
    container_name: openwhisk
    hostname: openwhisk
    network_mode: bridge
    image: openwhisk/standalone:nightly
    restart: always
    ports:
      - 3233:3233
      - 3232:3232
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openwhisk/:/root/.openwhisk

  pragmad:
    image: pragmad
    restart: always
    ports: 
      - 3030:3030
    environment:
      DAEMON_HOSTNAME: localhost
      DAEMON_PORT: 3030
      DAEMON_PG_URI: 'jdbc:postgresql://pragma-postgres:5432/test' 
      DAEMON_PG_USER: 'test' 
      DAEMON_WSK_API_HOST: 'localhost:3233' 
      DAEMON_WSK_AUTH_TOKEN: '23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP' 
      DAEMON_PG_PASSWORD: 'test' 
      DAEMON_WSK_API_VERSION: 1
    depends_on:
      - openwhisk
      - pragma_postgres