[book]
authors = ["Anas Albarghouthy, Mohammed Tabaza"]
language = "en"
multilingual = false
src = "."
title = "Heavenly-x"

[build]

[output.html]   
additional-js = ["./src/main.js"]
additional-css = ["./src/main.css"]
default-theme = "ayu"